### ISSUE TITLE
为啥没有pnet

### ISSUE THREAD

**Issue by shineway14** [DevinHiscene/openVINO-MTCNN-Rnet-Onet#2]

**Comment by DevinHiscene** [comment]
When deploying original P-net of Mtcnn, we could using multi-scales as inputs.
But, as i know, openVINO dose not support changeable inputs, in other words, you must give a fixed shape of input for openVINO.
Any way, you could initialize lots of P-nets with inputs of different scale, but it is an inefficient way considered about time and space.
A better solution is using another inputs-changeable inference such as DNN in opencv for deploying P-net.

**Comment by shineway14** [comment]
> When deploying original P-net of Mtcnn, we could using multi-scales as inputs.
> But, as i know, openVINO dose not support changeable inputs, in other words, you must give a fixed shape of input for openVINO.
> Any way, you could initialize lots of P-nets with inputs of different scale, but it is an inefficient way considered about time and space.
> A better solution is using another inputs-changeable inference such as DNN in opencv for deploying P-net.

**Comment by shineway14** [comment]
> When deploying original P-net of Mtcnn, we could using multi-scales as inputs.
> But, as i know, openVINO dose not support changeable inputs, in other words, you must give a fixed shape of input for openVINO.
> Any way, you could initialize lots of P-nets with inputs of different scale, but it is an inefficient way considered about time and space.
> A better solution is using another inputs-changeable inference such as DNN in opencv for deploying P-net.Thanks,Have you compared mtcnn with LFFD
